name: ${name}
version: ${version}
main: de.codecrafter47.taboverlay.bukkit.AdvancedTabOverlay
author: CodeCrafter47
api-version: 1.13
description: |
  Allows to customize the tab overlay.
depend: ["ProtocolLib"]
softdepend:
  - Factions
  - Vault
  - VanishNoPacket
  - SuperVanish
  - PremiumVanish
  - PlayerPoints
  - PlaceholderAPI
  - SimpleClans
  - Essentials
  - Multiverse-Core
  - ASkyBlock
  - CMI
loadbefore:
  - TAB
commands:
  ato:
    aliases: ["advancedtaboverlay"]
    description: Administrative command of AdvanceTabOverlay
    permission: advancedtaboverlay.admin
    usage: /ato [info|reload]